name: Build HNO_Sun for Mac

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install PyInstaller
        run: pip install pyinstaller
      
      - name: Build Mac App
        run: pyinstaller --onefile --windowed --icon=sun.ico --name "HNO_Sun" b.py
      
      - name: Upload Mac App
        uses: actions/upload-artifact@v4
        with:
          name: My_Sun-macOS
          path: dist/HNO_Sun
